# kafka3-zookeeper
kafka3-zookeeper-up:
	@docker-compose -f ./kafka3-zookeeper/docker-compose.yml up --remove-orphans -d

kafka3-zookeeper-down:
	@docker-compose -f ./kafka3-zookeeper/docker-compose.yml down -v


# kafka3-zookeeper-akhq
kafka3-zookeeper-akhq-up:
	@docker-compose -f ./kafka3-zookeeper-akhq/docker-compose.yml up --remove-orphans -d

kafka3-zookeeper-akhq-down:
	@docker-compose -f ./kafka3-zookeeper-akhq/docker-compose.yml down -v


# kafka-zookeeper
kafka-zookeeper-up:
	@docker-compose -f ./kafka-zookeeper/docker-compose.yml up --remove-orphans -d

kafka-zookeeper-down:
	@docker-compose -f ./kafka-zookeeper/docker-compose.yml down -v

# kafka-zookeeper
kafka-zookeeper-kafdrop-up:
	@docker-compose -f ./kafka-zookeeper-kafdrop/docker-compose.yml up --remove-orphans -d

kafka-zookeeper-kafdrop-down:
	@docker-compose -f ./kafka-zookeeper-kafdrop/docker-compose.yml down -v