# kafka-kraft-noauth
kafka-kraft-noauth-up:
	@docker-compose -f ./kafka-kraft-noauth/docker-compose.yml up --remove-orphans -d

kafka-kraft-noauth-down:
	@docker-compose -f ./kafka-kraft-noauth/docker-compose.yml down -v

# kafka-kraft-sasl-plain
kafka-kraft-sasl-plain-up:
	@docker-compose -f ./kafka-kraft-sasl-plain/docker-compose.yml up --remove-orphans -d

kafka-kraft-sasl-plain-down:
	@docker-compose -f ./kafka-kraft-sasl-plain/docker-compose.yml down -v

# kafka-zookeeper-sasl-plain
kafka-zookeeper-sasl-plain-up:
	@docker-compose -f ./kafka-zookeeper-sasl-plain/docker-compose.yml up --remove-orphans -d

kafka-zookeeper-sasl-plain-down:
	@docker-compose -f ./kafka-zookeeper-sasl-plain/docker-compose.yml down -v
